
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan_parfume;


import java.awt.Color;


/**
 *
 * @author Luthfi Ramadhan
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MENU() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);
        
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelstok = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelinput = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelkasir = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        labeladmin = new javax.swing.JLabel();
        LabelDesktop = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("L`PERFUME");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 5));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        labelstok.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labelstok.setForeground(new java.awt.Color(255, 255, 255));
        labelstok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/01stok.png"))); // NOI18N
        labelstok.setText("STOK");
        labelstok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelstokMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelstokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelstokMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelstok, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelstok)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        labelinput.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labelinput.setForeground(new java.awt.Color(255, 255, 255));
        labelinput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelinput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/02input.png"))); // NOI18N
        labelinput.setText("BARANG");
        labelinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelinputMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelinputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelinputMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelinput)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelinput)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        labelkasir.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labelkasir.setForeground(new java.awt.Color(255, 255, 255));
        labelkasir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelkasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/03kasir.png"))); // NOI18N
        labelkasir.setText("KASIR");
        labelkasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelkasirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelkasirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelkasirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelkasir, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelkasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        labeladmin.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labeladmin.setForeground(new java.awt.Color(255, 255, 255));
        labeladmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeladmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/suplier.png"))); // NOI18N
        labeladmin.setText("ADMIN");
        labeladmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeladminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeladminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeladminMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labeladmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labeladmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        LabelDesktop.setFont(new java.awt.Font("Roland", 1, 60)); // NOI18N
        LabelDesktop.setForeground(new java.awt.Color(51, 51, 51));
        LabelDesktop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDesktop.setText("L`PERFUME");

        jLabel1.setText("PROYEK_CATDOG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(LabelDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labeladminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeladminMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        ADMIN OPEN = new ADMIN();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labeladminMouseClicked

    private void labelstokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelstokMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        STOK OPEN = new STOK();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labelstokMouseClicked

    private void labelinputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelinputMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        INPUT OPEN = new INPUT();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labelinputMouseClicked

    private void labelkasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkasirMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        KASIR OPEN = new KASIR();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labelkasirMouseClicked

    private void labelstokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelstokMouseEntered
        // TODO add your handling code here:
        labelstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/01stok_bw.png")));
        labelstok.setForeground(Color.gray);
    }//GEN-LAST:event_labelstokMouseEntered

    private void labelstokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelstokMouseExited
        // TODO add your handling code here:
        labelstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/01stok.png")));
        labelstok.setForeground(Color.white);
    }//GEN-LAST:event_labelstokMouseExited

    private void labelinputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelinputMouseEntered
        // TODO add your handling code here:
        labelinput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/02input_bw.png")));
        labelinput.setForeground(Color.gray);
    }//GEN-LAST:event_labelinputMouseEntered

    private void labelinputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelinputMouseExited
        // TODO add your handling code here:
        labelinput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/02input.png")));
        labelinput.setForeground(Color.white);
    }//GEN-LAST:event_labelinputMouseExited

    private void labelkasirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkasirMouseEntered
        // TODO add your handling code here:
        labelkasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/03kasir_bw.png")));
        labelkasir.setForeground(Color.gray);
    }//GEN-LAST:event_labelkasirMouseEntered

    private void labelkasirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkasirMouseExited
        // TODO add your handling code here:
        labelkasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/03kasir.png")));
        labelkasir.setForeground(Color.white);
    }//GEN-LAST:event_labelkasirMouseExited

    private void labeladminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeladminMouseEntered
        // TODO add your handling code here:
        labeladmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/admin_bw.png")));
        labeladmin.setForeground(Color.gray);
    }//GEN-LAST:event_labeladminMouseEntered

    private void labeladminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeladminMouseExited
        // TODO add your handling code here:
        labeladmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/admin.png")));
        labeladmin.setForeground(Color.white);
    }//GEN-LAST:event_labeladminMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labeladmin;
    private javax.swing.JLabel labelinput;
    private javax.swing.JLabel labelkasir;
    private javax.swing.JLabel labelstok;
    // End of variables declaration//GEN-END:variables
}
